### ISSUE TITLE
Parse error on opening APK (Pre release v0.1.0)

### ISSUE THREAD

**Issue by wright-david** [pazaan/Medtronic640gUploader#10]
Pre-release v0.1.0  commit f309f23

Both Matt and I have Parse error when trying to open this APK on a device

**Comment by HenrikHL** [comment]
I also get a "Parse error" - There was a problem parsing the package

**Comment by kellylove1** [comment]
Hello,
I also have problems with the installation of the app.
The system replies: error during package analysis.
Thank you

**Comment by pazaan** [comment]
Hi guys. I can't repro on my J1 Ace running KitKat. I've both downloaded and launched directly from the GitHub release page, as well as downloading and copying with Android File Transfer. I've uploaded a new signed APK. Can you retry with that one?

**Comment by HenrikHL** [comment]
It's working now. Why is it necessary to get access to: find accounts and read contacts?

**Comment by pazaan** [comment]
It's not. That's left over from where I grabbed the template from. I'll remove the access request for it and release an update.
