### ISSUE TITLE
Incorrect username or password

### ISSUE THREAD

**Issue by HenrikHL** [pazaan/Medtronic640gUploader#11]
When trying to register the USB stick you have to enter Carelink UserName and Password - even though the correct credentials have been inserted (tested on the carelink.minimed.eu) it says "The UserName or Password is incorrect"?
Where is the App trying to verify the credentials? Could it be because it is verifying against a ".com" server instead of a ".eu" server?

**Comment by HenrikHL** [comment]
Maybe it could also be a problem with my username - it has "special" characters in it:
HenrikHelmø

**Comment by pazaan** [comment]
It's _only_ valid for the .eu server. Have you checked that you can log into the .eu CareLink server with the username and credentials provided? The other unfortunately problem is that if there's an internal CareLink error, it returns this error message - this is a problem with the CareLink server, not with the app.

**Comment by HenrikHL** [comment]
If have just tested on the Carelink server (.eu) and it logs into it fine... :-(

**Comment by HenrikHL** [comment]
Could the special character in my UserName be the problem? It depends on how the characters are sent/read in the App... Has anyone else with special characters succeeded in logging in?

**Comment by pazaan** [comment]
It could indeed be the special character. I've created a new account with the ø character, and I'm having the same problem. Looking into a fix.

**Comment by HenrikHL** [comment]
Did you upload a new version? I tried downloading 0.1.0 - but it doesn't seem to be fixed...

**Comment by pazaan** [comment]
Try https://github.com/pazaan/Medtronic640gUploader/releases/download/v0.1.1/medtronic640g-uploader-signed.apk

**Comment by HenrikHL** [comment]
Tried it - at first it seemed to work. Waiting a loong time to retrieve keys. But then:-( it came up with same error message. And it does this after a restart quite quickly - seems like it doesn't reach the USB anymore - maybe it is hitting a cache instead?!?

**Comment by HenrikHL** [comment]
Also tried to re-install the .apk

**Comment by HenrikHL** [comment]
also tried to clear app-data and cache - no luck :-(

**Comment by kellylove1** [comment]
I have the same problem,
Login error with the app but if I try to login to carelink.minimed.eu it work.
