### ISSUE TITLE
API base URI  'template' in Preferences

### ISSUE THREAD

**Issue by wright-david** [pazaan/Medtronic640gUploader#17]
This should be updated to
YOURAPISECRET@https://YOURWEBSITE.azurewebsites.net/api/v1/

**Comment by pazaan** [comment]
As discussed in the Gitter channel, make it YOURAPISECRET@https://YOUR.NIGHTSCOUT.SITE/api/v1/

**Comment by pazaan** [comment]
Created #19 as a possible future enhancement.
